# Processo ETL Completo

In [74]:
import pandas as pd
import glob
import numpy as np

## Extract
Aqui eu defino o caminho onde estão os `.csv` e retorno uma lista deles usando o glob.
Após isso eu concateno(junto) os arquivos em um só DataFrame.
E por fim eu carrego um arquivo somente que foi a junção dos anteriores para a camada Raw

In [75]:
path_files= "../data/*.csv"
files= glob.glob(path_files)
print(files)
df_fatura = pd.concat((pd.read_csv(f,sep=";") for f in files),ignore_index=True)
df_fatura.to_csv("../data/raw/faturas.csv",sep="|")
df_fatura

['../data\\Fatura_2025-03-20.csv', '../data\\Fatura_2025-04-20.csv', '../data\\Fatura_2025-05-20.csv', '../data\\Fatura_2025-06-20.csv', '../data\\Fatura_2025-07-20.csv', '../data\\Fatura_2025-08-20.csv', '../data\\Fatura_2025-09-20.csv', '../data\\Fatura_2025-10-20.csv', '../data\\Fatura_2025-11-20.csv', '../data\\Fatura_2025-12-20.csv', '../data\\Fatura_2026-01-20.csv', '../data\\Fatura_2026-02-20.csv']

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$)
0,12/10/2024,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.00,0.00,52.99
1,28/10/2024,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.00,0.00,162.00
2,16/11/2024,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.00,0.00,48.49
3,26/11/2024,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.00,0.00,498.08
4,24/01/2025,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.00,0.00,633.33
...,...,...,...,...,...,...,...,...,...
1940,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53
1941,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39
1942,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53
1943,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,-3329.39
1944,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39

## TRANSFORM

In [76]:
df_fatura = df_fatura.rename(columns={"Data de Compra":"data_compra","Nome no Cartão":"nome","Categoria":"tipo","Parcela":"parcela",
                                      "Valor (em US$)":"valor_usd","Valor (em R$)":"valor_brl","Cotação (em R$)":"cotacao_usd"})

In [77]:
df_fatura["data_compra"] = pd.to_datetime(df_fatura["data_compra"],errors="raise",dayfirst="True")

In [78]:
df_fatura = df_fatura.drop(columns=["Final do Cartão","Descrição"])
df_fatura

,data_compra,nome,tipo,parcela,valor_usd,cotacao_usd,valor_brl
0,2024-10-12,VIN DIESEL,Departamento / Desconto,5/10,0.00,0.00,52.99
1,2024-10-28,VIN DIESEL,Assistência médica e odontológica,5/10,0.00,0.00,162.00
2,2024-11-16,VIN DIESEL,Supermercados / Mercearia / Padarias / Lojas d...,4/10,0.00,0.00,48.49
3,2024-11-26,VIN DIESEL,Relacionados a Automotivo,4/4,0.00,0.00,498.08
4,2025-01-24,VIN DIESEL,Relacionados a Automotivo,2/3,0.00,0.00,633.33
...,...,...,...,...,...,...,...
1940,2026-02-01,EVA MENDES,Serviços financeiros,Única,0.00,0.00,116.53
1941,2026-02-01,EVA MENDES,Serviços financeiros,Única,608.92,5.47,3329.39
1942,2026-02-01,EVA MENDES,Serviços financeiros,Única,0.00,0.00,116.53
1943,2026-02-01,EVA MENDES,Serviços financeiros,Única,608.92,5.47,-3329.39
1944,2026-02-01,EVA MENDES,Serviços financeiros,Única,608.92,5.47,3329.39

In [79]:
dim_titular = df_fatura[["nome"]]
dim_titular = dim_titular.drop_duplicates()
dim_titular["sk_titular"]= range(1,len(dim_titular)+1)
dim_titular = dim_titular[["sk_titular","nome"]].reset_index(drop=True)
dim_titular

   sk_titular             nome
0           1       VIN DIESEL
1           2  CHARLIZE THERON
2           3      BRIAN TYLER
3           4       EVA MENDES

In [80]:
dim_categoria = df_fatura[["tipo"]]
dim_categoria= dim_categoria.drop_duplicates().reset_index(drop=True)
dim_categoria = dim_categoria[dim_categoria["tipo"]!= "-"]
dim_categoria["sk_categoria"] =range(1,len(dim_categoria)+1)
dim_categoria = dim_categoria[["sk_categoria","tipo"]]
dim_categoria

    sk_categoria                                               tipo
0              1                            Departamento / Desconto
1              2                  Assistência médica e odontológica
2              3  Supermercados / Mercearia / Padarias / Lojas d...
3              4                          Relacionados a Automotivo
4              5                     Restaurante / Lanchonete / Bar
6              6                                         Transporte
7              7                  Materiais de construção para casa
8              8                               Empresa para empresa
9              9                               Especialidade varejo
10            10                                         Associação
11            11                                T&E Companhia aérea
12            12                                           Elétrico
13            13                       Casa / Escritório Mobiliário
14            14                                             Seguro
15            15                                        Educacional
16            16                                 Vestuário / Roupas
17            17                                  Serviços pessoais
18            18                                     Entretenimento
19            19                             Serviços Profissionais
20            20              TV por assinatura / Serviços de rádio
21            21                                         Construção
22            22                                   Empresa serviços
23            23                                 Consertos em Geral
24            24                                          T&E Hotel
25            25                               Antigos / Peão Lojas
26            26                                            Governo
27            27                                            Aluguel
28            28                     Arte / Artesanato / Passatempo
29            29                                         Automotivo
30            30                                         Recreativo
31            31                                                T&E
32            32                       Serviços de telecomunicações
33            33                                   Marketing Direto
34            34                               Limpeza / Lavanderia
35            35                               Serviços financeiros

In [81]:
dim_data = df_fatura[["data_compra"]]
dim_data = dim_data.assign(
    sk_data = dim_data["data_compra"],
    ano = dim_data["data_compra"].dt.year.astype(int),
    mes = dim_data["data_compra"].dt.month.astype(int),
    dia = dim_data["data_compra"].dt.day.astype(int),
    semestre = np.where(dim_data["data_compra"].dt.quarter>2,2,1),
    dia_da_semana= dim_data["data_compra"].dt.day_of_week
)

dim_data["sk_data"]= (
    dim_data["sk_data"]
    .astype(str)
    .str
    .replace("-","")
    .astype(int)
)
dim_data = dim_data.drop(columns=["data_compra"])
dim_data= dim_data.drop_duplicates()

In [82]:
fato_fatura = df_fatura.copy()
fato_fatura["data_compra"]= fato_fatura["data_compra"].astype(str).str.replace("-","").astype(int)
fato_fatura = fato_fatura.rename(columns={"data_compra":"sk_data"})
fato_fatura["parcela"] = fato_fatura["parcela"].replace("Única","1")
fato_fatura["parcela"]= fato_fatura["parcela"].str.split("/")
fato_fatura["parcela_atual"] = fato_fatura["parcela"].str.get(0).astype(int)
fato_fatura["parcelas_totais"]= fato_fatura["parcela"].str.get(1)
fato_fatura["parcelas_totais"] = fato_fatura["parcelas_totais"].fillna(1).astype(int)
fato_fatura = fato_fatura.drop(columns=["parcela"])
fato_fatura = fato_fatura.merge(dim_categoria,on="tipo",how="inner")
fato_fatura = fato_fatura.merge(dim_titular, on="nome",how="inner")
fato_fatura = fato_fatura.merge(dim_data,on="sk_data",how="inner")
fato_fatura = fato_fatura[["sk_titular","sk_categoria","sk_data","valor_brl","valor_usd","cotacao_usd","parcela_atual","parcelas_totais"]]
fato_fatura = fato_fatura.drop_duplicates().reset_index(drop=True)
fato_fatura = fato_fatura[fato_fatura["valor_brl"]>0]
fato_fatura

,sk_titular,sk_categoria,sk_data,valor_brl,valor_usd,cotacao_usd,parcela_atual,parcelas_totais
0,1,1,20241012,52.99,0.00,0.00,5,10
1,1,2,20241028,162.00,0.00,0.00,5,10
2,1,3,20241116,48.49,0.00,0.00,4,10
3,1,4,20241126,498.08,0.00,0.00,4,4
4,1,4,20250124,633.33,0.00,0.00,2,3
...,...,...,...,...,...,...,...,...
1872,4,2,20260130,103.34,0.00,0.00,1,3
1873,4,2,20260130,12.90,0.00,0.00,1,1
1874,4,10,20260201,106.87,0.00,0.00,1,1
1876,4,35,20260201,116.53,0.00,0.00,1,1
1877,4,35,20260201,3329.39,608.92,5.47,1,1

In [83]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

load_dotenv()
DB_SENHA= os.getenv("DB_SENHA")

db = create_engine(f"postgresql://eduar:{DB_SENHA}@localhost:5432/DW_Faturas")

## LOAD

In [84]:
dim_categoria.to_sql("dim_categoria",
                     con=db,
                     if_exists="delete_rows",
                     index=False)

DatabaseError: Execution failed on sql 'DELETE FROM dim_categoria': (psycopg2.errors.ForeignKeyViolation) update or delete on table "dim_categoria" violates foreign key constraint "fato_fatura_sk_categoria_fkey" on table "fato_fatura"
DETAIL:  Key (sk_categoria)=(1) is still referenced from table "fato_fatura".

[SQL: DELETE FROM dim_categoria]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
dim_titular.to_sql("dim_titular",
                   con=db,
                   if_exists="delete_rows",
                   index=False)

4

In [ ]:
dim_data.to_sql("dim_data",
                con=db,
                if_exists="delete_rows",
                index=False)

343

In [ ]:
fato_fatura.to_sql("fato_fatura",
                   con=db,
                   if_exists="delete_rows",
                   index=False)

874